# Chapter 3: Activation Functions

## ReLU Activation Function Code

The code representing a ReLU activation function is shown below:

In [1]:
inputs = [0,2,-1,3.3,-2.7,1.1,2.2,-100]
output = [i if i > 0 else 0 for i in inputs]
print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


Or even more simplier:

In [2]:
output = [max(0,i) for i in inputs]
print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


With Numpy it can get even simplier:

In [3]:
import numpy as np
from nnfs.datasets import spiral_data
output = np.maximum(0,inputs)
print(output)

[0.  2.  0.  3.3 0.  1.1 2.2 0. ]


New we define Activation ReLU:

In [4]:
class ActivationReLU:
    def forward(self,inputs):
        self.output = np.maximum(0,inputs)

Let's first copy the snippets from previous chapter:

In [5]:
class LayerDense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1,n_neurons))
        
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

Let's apply our new activation function.

In [6]:
x, y = spiral_data(100,3)
dense1 = LayerDense(2,3)
activation1 = ActivationReLU()
dense1.forward(x)
activation1.forward(dense1.output)
print(activation1.output[:5])

[[0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.23014976e-04 6.87062708e-05 1.74907226e-03]
 [1.55018282e-03 0.00000000e+00 3.82103239e-03]
 [2.33195441e-03 0.00000000e+00 5.73313794e-03]
 [1.12948816e-04 4.56771368e-04 6.36783180e-03]]
