# Neural Network From Scrath in Python

## Chapter 1

In [1]:
import numpy as np

### A single neuron with Numpy
For a single neuron we have inputs, weights and bias:

In [2]:
inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

Now we compute the output:

In [3]:
output = np.dot(weights, inputs) + bias
print(output)

4.8


### A layer of neurons with Numpy
In a layer of neurons there are 4 weights for each neuron with respect to 4 input parameters.

In [4]:
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1.0], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

The output would be the dot product between weights and inputs plus the bias.

In [5]:
layer_outputs = np.dot(weights, inputs) + biases
print(layer_outputs)

[4.8   1.21  2.385]


### A batch of Data

In [6]:
batch = np.array([[1, 2, 3, 2.5], [2.0, 5.0, -1.0, 2.0], [-1.5, 2.7, 3.3, -0.8]])
weights = np.array([[0.2, 0.8, -0.5, 1.0], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]])

The outputs would be:

In [7]:
outputs = np.dot(batch, weights.T)+biases
print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
